apiVersion: apps/v1
kind: Deployment # replica do replicaset.yaml
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template: # template do pod que queremos executar
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "lkosaka/hello-go:v7"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000 # porta do container, não confundir com do services
            periodSeconds: 5 # de quanto em quanto tempo será realizado a verificação
            failureThreshold: 3 # quantas vezes precisa dar erro para reiniciar
            timeoutSeconds: 1 # quanto tempo limite para completar a requisição, quando dar erro entra no contador do failureThreshold
            successThreshold: 1 # quantas vezes precisa testar para dar ok

          envFrom:
            - configMapRef:
                name: configmap-family
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true

      volumes:
        - name: config 
          configMap:
            name: configmap-family 
            items:
              - key: members
                path: "family.txt"