apiVersion: v1
kind: Pod
metadata:
  name: "goserver" # nome do pod
  labels:
    app: "goserver" # ajuda no filtro, busca e regras
spec:
  containers:
    - name: goserver
      image: "lkosaka/hello-go:v1"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
