apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver # nome do replicaset
  labels:
    app: goserver 
spec:
  selector: # filtra os objetos por label
    matchLabels:
      app: goserver
  replicas: 3
  template: # template do pod que queremos executar
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "lkosaka/hello-go:v1"